# Generated by Django 5.1.2 on 2024-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria_web', '0002_denuncia_delete_denuncias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/denuncia'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
