# Generated by Django 5.1.2 on 2024-10-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria_web', '0003_alter_denuncia_arquivo_alter_denuncia_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='comentario',
            new_name='comentari',
        ),
    ]
