# Generated by Django 5.1.2 on 2024-10-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria_web', '0004_rename_comentario_denuncia_comentari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='comentari',
            new_name='comentario',
        ),
    ]
