# Generated by Django 5.1.2 on 2024-10-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria_web', '0005_rename_comentari_denuncia_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField(max_length=15)),
                ('tipo_reclamacao', models.TextField(max_length=20)),
                ('classificacao_insatisfacao', models.IntegerField(max_length=1)),
                ('descricao', models.TextField()),
                ('preferencia_contato', models.TextField(max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
