# Generated by Django 5.1.2 on 2024-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria_web', '0007_alter_reclamacao_classificacao_insatisfacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elogio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField(max_length=15)),
                ('classificacao_satisfacao', models.IntegerField()),
                ('descricao', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField(max_length=15)),
                ('descricao', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
