# Generated by Django 5.1.2 on 2024-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria_web', '0008_elogio_sugestao'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elogio',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='elogio',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reclamacao',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sugestao',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sugestao',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
