# Generated by Django 5.1.2 on 2024-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvidoria_web', '0010_alter_denuncia_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
